DROP TABLE IF EXISTS article;

CREATE TABLE article (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  head TEXT NOT NULL,
  body TEXT NOT NULL,
  icon TEXT NOT NULL,
  r INTEGER NOT NULL,
  g INTEGER NOT NULL,
  b INTEGER NOT NULL
);